#!/usr/bin/env python3
"""Render `cover.png` thumbnails for catalog models from their STL files.

The catalog shows whatever image it finds in a model folder. Downloaded models
usually ship a photo, but anything generated by a script arrives as bare
geometry and lands in the grid as an empty placeholder. This walks the models
tree, finds those, and renders a small shaded preview next to the mesh.

    python thumbnail.py --all                    # every model missing a cover
    python thumbnail.py --all --force            # re-render everything
    python thumbnail.py ../../models/kitchen/dog-cup
    python thumbnail.py path/to/thing.stl -o cover.png

Rendering is done with numpy + matplotlib rather than a GL context, so it works
over SSH and in containers with no display attached.

    uv venv .venv && uv pip install --python .venv/bin/python numpy matplotlib
"""

from __future__ import annotations

import argparse
import struct
import sys
from fnmatch import fnmatch
from pathlib import Path

try:
    import numpy as np
except ImportError:  # pragma: no cover - dependency hint
    sys.exit("numpy is required: uv pip install numpy matplotlib")

# The models root, relative to this file (catalog/scripts/thumbnail.py).
DEFAULT_MODELS_ROOT = Path(__file__).resolve().parents[2] / "models"

IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
COVER_NAME = "cover.png"


# --------------------------------------------------------------------------
# STL loading
# --------------------------------------------------------------------------


def load_stl(path: Path) -> np.ndarray:
    """Return an (n, 3, 3) array of triangle vertices.

    Handles both STL flavours. The ASCII check is deliberately not just "starts
    with `solid`" — plenty of binary exporters write that word into the header
    too, so we also require the file to be big enough to *be* the triangle count
    it claims.
    """
    raw = path.read_bytes()
    if len(raw) < 84:
        raise ValueError(f"{path.name}: too small to be an STL")

    (declared,) = struct.unpack("<I", raw[80:84])
    looks_binary = len(raw) == 84 + declared * 50
    if not looks_binary and raw.lstrip()[:5].lower() == b"solid":
        return _load_ascii_stl(raw)
    return _load_binary_stl(raw, declared)


def _load_binary_stl(raw: bytes, count: int) -> np.ndarray:
    # Each facet is 50 bytes: normal (3f), 3 vertices (9f), attribute (uint16).
    # Read them as a structured array in one shot and drop everything but the
    # vertices — the stored normals are frequently wrong, so we recompute them.
    dtype = np.dtype([("normal", "<3f4"), ("vertices", "<9f4"), ("attr", "<u2")])
    facets = np.frombuffer(raw, dtype=dtype, count=count, offset=84)
    return facets["vertices"].reshape(-1, 3, 3).astype(np.float64)


def _load_ascii_stl(raw: bytes) -> np.ndarray:
    vertices = [
        [float(part) for part in line.split()[1:4]]
        for line in raw.decode("utf-8", "replace").splitlines()
        if line.strip().startswith("vertex")
    ]
    if not vertices or len(vertices) % 3:
        raise ValueError("ASCII STL has a vertex count that is not a multiple of 3")
    return np.asarray(vertices, dtype=np.float64).reshape(-1, 3, 3)


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def render(triangles: np.ndarray, out_path: Path, size: int = 640) -> None:
    """Render every face. Do not be tempted to subsample the triangle list to
    speed this up — dropping faces punches holes straight through a dense
    surface, and there is nothing to gain: a 128k-face tray renders in well
    under a second."""
    import matplotlib

    matplotlib.use("Agg")  # no display needed
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection

    # Lambert shading against a fixed light, so curvature is readable.
    edge1 = triangles[:, 1] - triangles[:, 0]
    edge2 = triangles[:, 2] - triangles[:, 0]
    normals = np.cross(edge1, edge2)
    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    normals = np.divide(normals, lengths, out=np.zeros_like(normals), where=lengths > 0)

    light = np.array([-0.3, -0.6, 0.75])
    light /= np.linalg.norm(light)
    intensity = np.clip(np.abs(normals @ light), 0.0, 1.0)
    shade = 0.35 + 0.65 * intensity  # keep unlit faces visible, not black

    base = np.array([0.92, 0.45, 0.13])  # the catalog's accent orange
    colors = np.clip(shade[:, None] * base[None, :], 0, 1)

    fig = plt.figure(figsize=(size / 100, size / 100), dpi=100)
    axes = fig.add_subplot(111, projection="3d")
    collection = Poly3DCollection(triangles, facecolors=colors, linewidths=0)
    axes.add_collection3d(collection)

    # Fit each axis to its own extent and carry the real proportions over into
    # the box aspect. Forcing a cube instead would letterbox flat parts into a
    # sliver in the middle of the image.
    points = triangles.reshape(-1, 3)
    low, high = points.min(axis=0), points.max(axis=0)
    extents = np.maximum(high - low, 1e-6)
    pad = 0.03 * extents.max()
    axes.set_xlim(low[0] - pad, high[0] + pad)
    axes.set_ylim(low[1] - pad, high[1] + pad)
    axes.set_zlim(low[2] - pad, high[2] + pad)
    axes.set_box_aspect(extents / extents.max(), zoom=1.25)

    # A three-quarter view flatters most parts, but a keychain or a nameplate is
    # essentially a plate: seen from the side it collapses to an edge and the
    # lettering becomes unreadable. Tilt towards top-down as parts get flatter.
    flatness = float(extents[2] / max(extents[0], extents[1]))
    if flatness < 0.25:
        axes.view_init(elev=68, azim=-90)
    else:
        axes.view_init(elev=28, azim=-125)
    axes.set_axis_off()
    fig.subplots_adjust(left=0, right=1, bottom=0, top=1)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, transparent=True, dpi=100)
    plt.close(fig)


# --------------------------------------------------------------------------
# Model discovery
# --------------------------------------------------------------------------


DEFAULT_EXCLUDE = ["node_modules", "__pycache__", "venv", "build", "dist"]
DEFAULT_OUTPUT_DIRS = ["out", "output"]


def load_config(root: Path) -> tuple[list[str], list[str]]:
    """Read `exclude:` and `output_dirs:` from catalog.yaml.

    Returns (exclude, output_dirs).

    The folder rules live in two places — `walk()` in `lib/catalog.ts` and here
    — and the whole point of the config file is that they read the same list.
    PyYAML is optional: without it we fall back to the same defaults the app
    ships, which is right for every case except a hand-edited exclude list.
    """
    config = root.parent / "catalog.yaml"
    if not config.is_file():
        return DEFAULT_EXCLUDE, DEFAULT_OUTPUT_DIRS
    try:
        import yaml  # noqa: PLC0415 — optional dependency
    except ImportError:
        print(f"note: PyYAML not installed, ignoring {config}", file=sys.stderr)
        return DEFAULT_EXCLUDE, DEFAULT_OUTPUT_DIRS
    try:
        data = yaml.safe_load(config.read_text()) or {}
    except yaml.YAMLError as error:
        print(f"note: could not parse {config}: {error}", file=sys.stderr)
        return DEFAULT_EXCLUDE, DEFAULT_OUTPUT_DIRS

    def string_list(key: str, fallback: list[str]) -> list[str]:
        value = data.get(key)
        if not isinstance(value, list):
            return fallback
        return [item for item in value if isinstance(item, str)]

    return string_list("exclude", DEFAULT_EXCLUDE), string_list(
        "output_dirs", DEFAULT_OUTPUT_DIRS
    )


def is_excluded(name: str, rel_path: str, patterns: list[str]) -> bool:
    """Mirror of `isExcluded` in lib/config.ts."""
    if name.startswith("."):
        return True
    return any(
        fnmatch(rel_path, pattern) if "/" in pattern else fnmatch(name, pattern)
        for pattern in patterns
    )


def is_model_dir(path: Path, patterns: list[str], outputs: list[str], root: Path) -> bool:
    """A leaf folder — the same rule the web app uses.

    An output folder does not count as a subfolder here: `walk()` treats it as
    part of its parent, so a generator folder holding only `out/` is still a
    model and still wants a thumbnail.
    """
    for child in path.iterdir():
        if not child.is_dir():
            continue
        rel = str(child.relative_to(root)).replace("\\", "/")
        if is_excluded(child.name, rel, patterns) or is_excluded(
            child.name, rel, outputs
        ):
            continue
        return False
    return True


def find_model_dirs(root: Path, patterns: list[str], outputs: list[str]) -> list[Path]:
    found: list[Path] = []
    for path in sorted(root.rglob("*")):
        if not path.is_dir():
            continue
        rel = path.relative_to(root)
        # Skip the folder itself, and anything living inside a skipped one.
        if any(
            is_excluded(part, str(Path(*rel.parts[: i + 1])).replace("\\", "/"), patterns)
            or is_excluded(part, str(Path(*rel.parts[: i + 1])).replace("\\", "/"), outputs)
            for i, part in enumerate(rel.parts)
        ):
            continue
        if is_model_dir(path, patterns, outputs, root):
            found.append(path)
    return found


def has_image(model_dir: Path) -> bool:
    return any(
        child.suffix.lower() in IMAGE_SUFFIXES
        for child in model_dir.iterdir()
        if child.is_file()
    )


def pick_stl(model_dir: Path, outputs: list[str]) -> Path | None:
    """Largest STL belonging to the model — usually the most complete variant.

    Looks in the model folder itself and in its output folders, because a
    generator writes its meshes to `out/` and that is exactly the model whose
    thumbnail is missing.
    """
    candidates = [
        child
        for child in model_dir.iterdir()
        if child.is_file() and child.suffix.lower() == ".stl"
    ]
    for child in model_dir.iterdir():
        if child.is_dir() and is_excluded(
            child.name, child.name, outputs
        ):
            candidates.extend(
                f for f in child.rglob("*.stl") if f.is_file()
            )
    return max(candidates, key=lambda p: p.stat().st_size, default=None)


def thumbnail_model(model_dir: Path, force: bool, outputs: list[str]) -> str:
    cover = model_dir / COVER_NAME
    if not force and has_image(model_dir):
        return "skip: already has an image"

    stl = pick_stl(model_dir, outputs)
    if stl is None:
        return "skip: no STL to render"

    triangles = load_stl(stl)
    render(triangles, cover)
    return f"rendered {COVER_NAME} from {stl.name} ({len(triangles)} faces)"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "targets",
        nargs="*",
        type=Path,
        help="model folders or .stl files (default: --all)",
    )
    parser.add_argument(
        "--all", action="store_true", help="walk the whole models tree"
    )
    parser.add_argument(
        "--root", type=Path, default=DEFAULT_MODELS_ROOT, help="models root"
    )
    parser.add_argument(
        "-o", "--output", type=Path, help="output path (single .stl target only)"
    )
    parser.add_argument(
        "--force", action="store_true", help="re-render even if an image exists"
    )
    args = parser.parse_args()

    if not args.targets and not args.all:
        parser.error("pass a model folder, or --all to do the whole tree")

    # A bare .stl with -o is the escape hatch for one-off renders.
    if args.output:
        if len(args.targets) != 1 or args.targets[0].suffix.lower() != ".stl":
            parser.error("--output takes exactly one .stl target")
        render(load_stl(args.targets[0]), args.output)
        print(f"{args.output}: rendered")
        return 0

    exclude, outputs = load_config(args.root)

    if args.all:
        if not args.root.is_dir():
            print(f"no models root at {args.root}", file=sys.stderr)
            return 1
        model_dirs = find_model_dirs(args.root, exclude, outputs)
    else:
        model_dirs = [t if t.is_dir() else t.parent for t in args.targets]

    failures = 0
    for model_dir in model_dirs:
        try:
            result = thumbnail_model(model_dir, args.force, outputs)
        except Exception as error:  # keep going; one bad mesh is not fatal
            result = f"FAILED: {error}"
            failures += 1
        try:
            label = model_dir.relative_to(args.root)
        except ValueError:
            label = model_dir
        print(f"{label}: {result}")

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
